name: pet_track_app
description: Veteriner Takip Uygulaması.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - /Users/mertkarahan/Desktop/pet_track_app/pet_track_app/lib/assets/odin_profilfoto.png